const allitems = [
    {
        id: 1,
        feature: '2% off',
        imgscr: './images/pro-1.jpg',
        product_bname: 'Fresho',
        product_name: 'Onion',
        vname: './images/veg.png',
        offer: '2%',
        price: 31.25,
        discount: 2,
        discountPrice: 31.25 - 2 / 100 * 31.25,
        quantity: 1
    },
    {
        id: 2,
        feature: '3% off',
        imgscr: './images/pro-2.jpg',
        product_bname: 'Fresho',
        product_name: 'Green Capsicum',
        vname: './images/veg.png',
        price: 20,
        discount: 3,
        discountPrice: 20 - 3 / 100 * 20,
        quantity: 1,
    },
    {
        id: 3,
        feature: '5% off',
        imgscr: './images/pro-3.jpg',
        product_bname: 'Fresho',
        product_name: 'Orange Carrot',
        vname: './images/veg.png',
        price: 23,
        discount: 5,
        discountPrice: 23 - 5 / 100 * 23,
        quantity: 1,
    },
    {
        id: 4,
        feature: '10% off',
        imgscr: './images/pro-4.jpg',
        product_bname: 'Fresho',
        product_name: 'Potato',
        vname: './images/veg.png',
        price: 22,
        discount: 10,
        discountPrice: 22 - 10 / 100 * 22,
        quantity: 1
    },
    {
        id: 5,
        feature: '4% off',
        imgscr: './images/pro-5.jpg',
        product_bname: 'Fresho',
        product_name: 'Palak',
        vname: './images/veg.png',
        price: 12,
        discount: 4,
        discountPrice: 12 - 4 / 100 * 12,
        quantity: 1
    },
    {
        id: 6,
        feature: '5% off',
        imgscr: './images/pro-6.jpg',
        product_bname: 'Fresho',
        product_name: 'Sugar',
        vname: './images/veg.png',
        price: 40,
        discount: 5,
        discountPrice: 40 - 5 / 100 * 40,
        quantity: 1
    },
    {
        id: 7,
        feature: '8% off',
        imgscr: './images/pro-7.jpg',
        product_bname: 'Fresho',
        product_name: 'Mango',
        vname: './images/veg.png',
        price: 55,
        discount: 8,
        discountPrice: 55 - 8 / 100 * 55,
        quantity: 1
    },
    {
        id: 8,
        feature: '15% off',
        imgscr: './images/pro-8.jpg',
        product_bname: 'Fresho',
        product_name: 'Refine Food Oil',
        vname: './images/veg.png',
        price: 180,
        discount: 15,
        discountPrice: 180 - 15 / 100 * 180,
        quantity: 1
    },
    {
        id: 9,
        feature: '12% off',
        imgscr: './images/pro-9.jpg',
        product_bname: 'Fresho',
        product_name: 'Nevia Soft Cream',
        vname: './images/veg.png',
        price: 220,
        discount: 12,
        discountPrice: 220 - 12 / 100 * 220,
        quantity: 1
    },
    {
        id: 10,
        feature: '8% off',
        imgscr: './images/pro-10.jpg',
        product_bname: 'Fresho',
        product_name: 'Nevia Body Protection',
        vname: './images/veg.png',
        price: 250,
        discount: 8,
        discountPrice: 250 - 8 / 100 * 250,
        quantity: 1
    },
    {
        id: 11,
        feature: '5% off',
        imgscr: './images/pro-12.jpg',
        product_bname: 'Fresho',
        product_name: 'Maggie Noddles',
        vname: './images/veg.png',
        price: 130,
        discount: 5,
        discountPrice: 130 - 5 / 100 * 130,
        quantity: 1,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. "
    },
    {
        id: 12,
        feature: '9% off',
        imgscr: './images/pro-13.jpg',
        product_bname: 'India Gate Basmate Rice',
        product_name: 'Basmati Dubar Rice',
        vname: './images/veg.png',
        price: 120,
        discount: 9,
        discountPrice: 120 - 9 / 100 * 120,
        quantity: 1,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. "
    },
    {
        id: 13,
        feature: '5% off',
        imgscr: './images/pro-14.jpg', 
        product_bname: 'Lays', 
        product_name: 'Lays Magic Masala', 
        vname: './images/veg.png', 
        price: 30, discount: 5, 
        discountPrice: 30 - 5 / 100 * 30, 
        quantity: 1, 
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. "
    },
    {
        id: 14,
        feature: '7% off',
        imgscr: './images/pro-15.jpg', 
        product_bname: 'Royal Organic', 
        product_name: 'Daliya', 
        vname: './images/veg.png', 
        price: 30, 
        discount: 7, 
        discountPrice: 30 - 7 / 100 * 30, 
        quantity: 1, 
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. "
    },
    {
        id: 15,
        feature: '10% off',
        imgscr: './images/pro-16.jpg', 
        product_bname: 'Safe Harvest', 
        product_name: 'Soya Rice', 
        vname: './images/veg.png', 
        price: 70, 
        discount: 10, 
        discountPrice: 70 - 10 / 100 * 70, 
        quantity: 1, 
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. "
    },
    {
        id: 16,
        feature: '5% off',
        imgscr: './images/pro-17.jpg', 
        product_bname: 'Aashirvaad Atta', 
        product_name: 'Aashirvaad Wheat Atta', 
        vname: './images/veg.png', 
        price: 170, 
        discount: 5, 
        discountPrice: 170 - 5 / 100 * 170, 
        quantity: 1, 
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit."
    },
]

export default allitems;